version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.32.1
    container_name: prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    depends_on:
      - pushgateway

  pushgateway:
    image: prom/pushgateway:v1.4.3
    container_name: pushgateway
    ports:
      - '9091:9091'

  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/config:/etc/grafana
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - prometheus
